# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeepEye.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 610)
        MainWindow.setMinimumSize(QtCore.QSize(740, 610))
        MainWindow.setMaximumSize(QtCore.QSize(740, 610))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 741, 571))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.main_tab = QtWidgets.QTabWidget(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy)
        self.main_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_tab.setAutoFillBackground(True)
        self.main_tab.setObjectName("main_tab")
        self.preprocess_tab = QtWidgets.QWidget()
        self.preprocess_tab.setObjectName("preprocess_tab")
        self.groupBox = QtWidgets.QGroupBox(self.preprocess_tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 731, 261))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(9, 19, 391, 231))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 371, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.classes_list = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.classes_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.classes_list.setUniformItemSizes(True)
        self.classes_list.setSelectionRectVisible(True)
        self.classes_list.setObjectName("classes_list")
        self.horizontalLayout.addWidget(self.classes_list)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_class_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.add_class_button.setObjectName("add_class_button")
        self.verticalLayout_2.addWidget(self.add_class_button)
        self.remove_class_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.remove_class_button.setObjectName("remove_class_button")
        self.verticalLayout_2.addWidget(self.remove_class_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(410, 20, 311, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 291, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.resize_width_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.resize_width_spinbox.setMaximum(99999)
        self.resize_width_spinbox.setProperty("value", 400)
        self.resize_width_spinbox.setObjectName("resize_width_spinbox")
        self.verticalLayout.addWidget(self.resize_width_spinbox)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.resize_height_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.resize_height_spinbox.setMaximum(99999)
        self.resize_height_spinbox.setProperty("value", 400)
        self.resize_height_spinbox.setObjectName("resize_height_spinbox")
        self.verticalLayout.addWidget(self.resize_height_spinbox)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(410, 140, 311, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 291, 81))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mask_prep_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.mask_prep_field.setObjectName("mask_prep_field")
        self.horizontalLayout_2.addWidget(self.mask_prep_field)
        self.mask_prep_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.mask_prep_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.mask_prep_browse_button.setObjectName("mask_prep_browse_button")
        self.horizontalLayout_2.addWidget(self.mask_prep_browse_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.fusion_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.fusion_button.setObjectName("fusion_button")
        self.verticalLayout_3.addWidget(self.fusion_button)
        self.groupBox_2 = QtWidgets.QGroupBox(self.preprocess_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 270, 731, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 20, 351, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(9, 19, 331, 96))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.aug_images_source_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.aug_images_source_field.setObjectName("aug_images_source_field")
        self.horizontalLayout_5.addWidget(self.aug_images_source_field)
        self.aug_images_source_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.aug_images_source_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.aug_images_source_browse_button.setObjectName("aug_images_source_browse_button")
        self.horizontalLayout_5.addWidget(self.aug_images_source_browse_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.aug_seg_source_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.aug_seg_source_field.setObjectName("aug_seg_source_field")
        self.horizontalLayout_4.addWidget(self.aug_seg_source_field)
        self.aug_seg_source_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.aug_seg_source_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.aug_seg_source_browse_button.setObjectName("aug_seg_source_browse_button")
        self.horizontalLayout_4.addWidget(self.aug_seg_source_browse_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(370, 10, 261, 251))
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_8)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 241, 230))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.aug_images_nb_spinbox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.aug_images_nb_spinbox.setMinimum(1)
        self.aug_images_nb_spinbox.setMaximum(999999)
        self.aug_images_nb_spinbox.setObjectName("aug_images_nb_spinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aug_images_nb_spinbox)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.aug_rotation_range_spinbox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.aug_rotation_range_spinbox.setMaximum(360)
        self.aug_rotation_range_spinbox.setObjectName("aug_rotation_range_spinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.aug_rotation_range_spinbox)
        self.aug_horizontal_spinbox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.aug_horizontal_spinbox.setMaximum(100)
        self.aug_horizontal_spinbox.setObjectName("aug_horizontal_spinbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.aug_horizontal_spinbox)
        self.aug_vertical_spinbox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.aug_vertical_spinbox.setMaximum(100)
        self.aug_vertical_spinbox.setObjectName("aug_vertical_spinbox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.aug_vertical_spinbox)
        self.aug_zoom_spinbox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.aug_zoom_spinbox.setMaximum(100)
        self.aug_zoom_spinbox.setObjectName("aug_zoom_spinbox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.aug_zoom_spinbox)
        self.aug_shear_spinbox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.aug_shear_spinbox.setMaximum(360)
        self.aug_shear_spinbox.setObjectName("aug_shear_spinbox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.aug_shear_spinbox)
        self.aug_fill_combobox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.aug_fill_combobox.setObjectName("aug_fill_combobox")
        self.aug_fill_combobox.addItem("")
        self.aug_fill_combobox.addItem("")
        self.aug_fill_combobox.addItem("")
        self.aug_fill_combobox.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.aug_fill_combobox)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.aug_width_spinbox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.aug_width_spinbox.setMaximum(99999)
        self.aug_width_spinbox.setProperty("value", 400)
        self.aug_width_spinbox.setObjectName("aug_width_spinbox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.aug_width_spinbox)
        self.aug_height_spinbox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.aug_height_spinbox.setMaximum(99999)
        self.aug_height_spinbox.setProperty("value", 400)
        self.aug_height_spinbox.setObjectName("aug_height_spinbox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.aug_height_spinbox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 140, 351, 121))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(9, 19, 331, 96))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.aug_images_dest_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.aug_images_dest_field.setObjectName("aug_images_dest_field")
        self.horizontalLayout_6.addWidget(self.aug_images_dest_field)
        self.aug_images_dest_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.aug_images_dest_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.aug_images_dest_browse_button.setObjectName("aug_images_dest_browse_button")
        self.horizontalLayout_6.addWidget(self.aug_images_dest_browse_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.aug_seg_dest_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.aug_seg_dest_field.setObjectName("aug_seg_dest_field")
        self.horizontalLayout_7.addWidget(self.aug_seg_dest_field)
        self.aug_seg_dest_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.aug_seg_dest_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.aug_seg_dest_browse_button.setObjectName("aug_seg_dest_browse_button")
        self.horizontalLayout_7.addWidget(self.aug_seg_dest_browse_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.aug_button = QtWidgets.QPushButton(self.groupBox_2)
        self.aug_button.setGeometry(QtCore.QRect(640, 130, 82, 23))
        self.aug_button.setObjectName("aug_button")
        self.main_tab.addTab(self.preprocess_tab, "")
        self.train_tab = QtWidgets.QWidget()
        self.train_tab.setObjectName("train_tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.train_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 731, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_10 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 320))
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_10)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 711, 291))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_12 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 125))
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_12)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 15, 211, 101))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.train_images_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.train_images_field.setObjectName("train_images_field")
        self.horizontalLayout_9.addWidget(self.train_images_field)
        self.train_images_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.train_images_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.train_images_browse_button.setObjectName("train_images_browse_button")
        self.horizontalLayout_9.addWidget(self.train_images_browse_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.train_seg_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.train_seg_field.setObjectName("train_seg_field")
        self.horizontalLayout_10.addWidget(self.train_seg_field)
        self.train_seg_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.train_seg_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.train_seg_browse_button.setObjectName("train_seg_browse_button")
        self.horizontalLayout_10.addWidget(self.train_seg_browse_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.verticalLayout_12.addWidget(self.groupBox_12)
        self.groupBox_14 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_14.setMaximumSize(QtCore.QSize(16777215, 125))
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_14)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 15, 211, 101))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.label_18)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.eval_images_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.eval_images_field.setObjectName("eval_images_field")
        self.horizontalLayout_11.addWidget(self.eval_images_field)
        self.eval_images_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.eval_images_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.eval_images_browse_button.setObjectName("eval_images_browse_button")
        self.horizontalLayout_11.addWidget(self.eval_images_browse_button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_9.addWidget(self.label_19)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.eval_seg_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.eval_seg_field.setObjectName("eval_seg_field")
        self.horizontalLayout_12.addWidget(self.eval_seg_field)
        self.eval_seg_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.eval_seg_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.eval_seg_browse_button.setObjectName("eval_seg_browse_button")
        self.horizontalLayout_12.addWidget(self.eval_seg_browse_button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addWidget(self.groupBox_14)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_18 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_18.setMaximumSize(QtCore.QSize(16777215, 140))
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_18)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(9, 19, 211, 112))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.model_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget_13)
        self.model_combobox.setObjectName("model_combobox")
        self.verticalLayout_18.addWidget(self.model_combobox)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_18.addWidget(self.label_33)
        self.width_model_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_13)
        self.width_model_spinbox.setMinimum(1)
        self.width_model_spinbox.setMaximum(99999)
        self.width_model_spinbox.setProperty("value", 400)
        self.width_model_spinbox.setObjectName("width_model_spinbox")
        self.verticalLayout_18.addWidget(self.width_model_spinbox)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_18.addWidget(self.label_34)
        self.height_model_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_13)
        self.height_model_spinbox.setMinimum(1)
        self.height_model_spinbox.setMaximum(99999)
        self.height_model_spinbox.setProperty("value", 400)
        self.height_model_spinbox.setObjectName("height_model_spinbox")
        self.verticalLayout_18.addWidget(self.height_model_spinbox)
        self.verticalLayout_17.addWidget(self.groupBox_18)
        self.groupBox_19 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_19.setMaximumSize(QtCore.QSize(16777215, 55))
        self.groupBox_19.setObjectName("groupBox_19")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_19)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 211, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.existing_model_path_field = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.existing_model_path_field.setObjectName("existing_model_path_field")
        self.horizontalLayout_14.addWidget(self.existing_model_path_field)
        self.existing_model_path_browse_button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.existing_model_path_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.existing_model_path_browse_button.setObjectName("existing_model_path_browse_button")
        self.horizontalLayout_14.addWidget(self.existing_model_path_browse_button)
        self.verticalLayout_17.addWidget(self.groupBox_19)
        self.groupBox_21 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_21.setMaximumSize(QtCore.QSize(16777215, 55))
        self.groupBox_21.setObjectName("groupBox_21")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_21)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 211, 25))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.nb_class_spinbox = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.nb_class_spinbox.setMinimum(1)
        self.nb_class_spinbox.setMaximum(255)
        self.nb_class_spinbox.setObjectName("nb_class_spinbox")
        self.horizontalLayout_21.addWidget(self.nb_class_spinbox)
        self.verticalLayout_17.addWidget(self.groupBox_21)
        self.horizontalLayout_3.addLayout(self.verticalLayout_17)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_13 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_13.setMaximumSize(QtCore.QSize(16777215, 210))
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_13)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 211, 181))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_11.addWidget(self.label_22)
        self.batch_size_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.batch_size_spinbox.setMinimum(1)
        self.batch_size_spinbox.setMaximum(99999)
        self.batch_size_spinbox.setObjectName("batch_size_spinbox")
        self.verticalLayout_11.addWidget(self.batch_size_spinbox)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_11.addWidget(self.label_23)
        self.step_epoch_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.step_epoch_spinbox.setMinimum(1)
        self.step_epoch_spinbox.setMaximum(99999)
        self.step_epoch_spinbox.setObjectName("step_epoch_spinbox")
        self.verticalLayout_11.addWidget(self.step_epoch_spinbox)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_11.addWidget(self.label_24)
        self.epochs_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.epochs_spinbox.setMinimum(1)
        self.epochs_spinbox.setMaximum(99999)
        self.epochs_spinbox.setObjectName("epochs_spinbox")
        self.verticalLayout_11.addWidget(self.epochs_spinbox)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_11.addWidget(self.label_29)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.save_model_path_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.save_model_path_field.setObjectName("save_model_path_field")
        self.horizontalLayout_20.addWidget(self.save_model_path_field)
        self.save_model_path_browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.save_model_path_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.save_model_path_browse_button.setObjectName("save_model_path_browse_button")
        self.horizontalLayout_20.addWidget(self.save_model_path_browse_button)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.verticalLayout_13.addWidget(self.groupBox_13)
        self.train_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.train_button.setObjectName("train_button")
        self.verticalLayout_13.addWidget(self.train_button)
        self.eval_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.eval_button.setObjectName("eval_button")
        self.verticalLayout_13.addWidget(self.eval_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_6.addWidget(self.groupBox_10)
        self.groupBox_9 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_9)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 20, 710, 190))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 708, 188))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.train_logs_textedit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.train_logs_textedit.setGeometry(QtCore.QRect(0, 0, 710, 190))
        self.train_logs_textedit.setUndoRedoEnabled(False)
        self.train_logs_textedit.setReadOnly(True)
        self.train_logs_textedit.setObjectName("train_logs_textedit")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.groupBox_9)
        self.main_tab.addTab(self.train_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(0, 0, 731, 541))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox_15 = QtWidgets.QGroupBox(self.verticalLayoutWidget_12)
        self.groupBox_15.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_15.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_15.setObjectName("groupBox_15")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_15)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 601, 121))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.predict_model_path_field = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.predict_model_path_field.setObjectName("predict_model_path_field")
        self.horizontalLayout_16.addWidget(self.predict_model_path_field)
        self.predict_model_path_browse_button = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.predict_model_path_browse_button.setMinimumSize(QtCore.QSize(30, 0))
        self.predict_model_path_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.predict_model_path_browse_button.setObjectName("predict_model_path_browse_button")
        self.horizontalLayout_16.addWidget(self.predict_model_path_browse_button)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.predict_images_field = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.predict_images_field.setObjectName("predict_images_field")
        self.horizontalLayout_17.addWidget(self.predict_images_field)
        self.predict_images_browse_button = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.predict_images_browse_button.setMinimumSize(QtCore.QSize(30, 0))
        self.predict_images_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.predict_images_browse_button.setObjectName("predict_images_browse_button")
        self.horizontalLayout_17.addWidget(self.predict_images_browse_button)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.saved_seg_field = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.saved_seg_field.setObjectName("saved_seg_field")
        self.horizontalLayout_18.addWidget(self.saved_seg_field)
        self.saved_seg_browse_button = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.saved_seg_browse_button.setMinimumSize(QtCore.QSize(30, 0))
        self.saved_seg_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.saved_seg_browse_button.setObjectName("saved_seg_browse_button")
        self.horizontalLayout_18.addWidget(self.saved_seg_browse_button)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.saved_sup_field = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.saved_sup_field.setObjectName("saved_sup_field")
        self.horizontalLayout_19.addWidget(self.saved_sup_field)
        self.saved_sup_browse_button = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.saved_sup_browse_button.setMinimumSize(QtCore.QSize(30, 0))
        self.saved_sup_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.saved_sup_browse_button.setObjectName("saved_sup_browse_button")
        self.horizontalLayout_19.addWidget(self.saved_sup_browse_button)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.horizontalLayout_15.addWidget(self.groupBox_15)
        self.predict_button = QtWidgets.QPushButton(self.verticalLayoutWidget_12)
        self.predict_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.predict_button.setObjectName("predict_button")
        self.horizontalLayout_15.addWidget(self.predict_button)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.groupBox_20 = QtWidgets.QGroupBox(self.verticalLayoutWidget_12)
        self.groupBox_20.setMinimumSize(QtCore.QSize(0, 370))
        self.groupBox_20.setObjectName("groupBox_20")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBox_20)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 20, 710, 340))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 708, 338))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.predict_logs_textedit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.predict_logs_textedit.setGeometry(QtCore.QRect(0, 0, 710, 340))
        self.predict_logs_textedit.setUndoRedoEnabled(False)
        self.predict_logs_textedit.setReadOnly(True)
        self.predict_logs_textedit.setObjectName("predict_logs_textedit")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_14.addWidget(self.groupBox_20)
        self.main_tab.addTab(self.tab, "")
        self.horizontalLayout_8.addWidget(self.main_tab)
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setEnabled(False)
        self.progress_bar.setGeometry(QtCore.QRect(0, 570, 741, 20))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setObjectName("progress_bar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_save_conf = QtWidgets.QAction(MainWindow)
        self.action_save_conf.setObjectName("action_save_conf")
        self.action_load_conf = QtWidgets.QAction(MainWindow)
        self.action_load_conf.setObjectName("action_load_conf")

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DeepEye"))
        self.groupBox.setTitle(_translate("MainWindow", "Prépration des masques"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Classes"))
        self.add_class_button.setText(_translate("MainWindow", "+"))
        self.remove_class_button.setText(_translate("MainWindow", "-"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Redimensionnement"))
        self.label_2.setText(_translate("MainWindow", "Largeur (px)"))
        self.label.setText(_translate("MainWindow", "Hauteur (px)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Lancement"))
        self.label_3.setText(_translate("MainWindow", "Sauvegarder dans"))
        self.mask_prep_browse_button.setText(_translate("MainWindow", "..."))
        self.fusion_button.setText(_translate("MainWindow", "Fusion"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Augmentation des données"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Source"))
        self.label_4.setText(_translate("MainWindow", "Images"))
        self.aug_images_source_browse_button.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Segmentations"))
        self.aug_seg_source_browse_button.setText(_translate("MainWindow", "..."))
        self.groupBox_8.setTitle(_translate("MainWindow", "Paramètres"))
        self.label_8.setText(_translate("MainWindow", "Nb d\'images"))
        self.label_9.setText(_translate("MainWindow", "Intervalle de rotation (degrès)"))
        self.label_10.setText(_translate("MainWindow", "Décalage horizontal (%)"))
        self.label_11.setText(_translate("MainWindow", "Décalage vertical (%)"))
        self.label_12.setText(_translate("MainWindow", "Zoom (%)"))
        self.label_13.setText(_translate("MainWindow", "Déformation/Shear (degrès)"))
        self.label_14.setText(_translate("MainWindow", "Stratégie de remplissage"))
        self.aug_fill_combobox.setItemText(0, _translate("MainWindow", "constant"))
        self.aug_fill_combobox.setItemText(1, _translate("MainWindow", "nearest"))
        self.aug_fill_combobox.setItemText(2, _translate("MainWindow", "reflect"))
        self.aug_fill_combobox.setItemText(3, _translate("MainWindow", "wrap"))
        self.label_21.setText(_translate("MainWindow", "Largeur (px)"))
        self.label_30.setText(_translate("MainWindow", "Hauteur (px)"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Destination"))
        self.label_6.setText(_translate("MainWindow", "Images"))
        self.aug_images_dest_browse_button.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Segmentations"))
        self.aug_seg_dest_browse_button.setText(_translate("MainWindow", "..."))
        self.aug_button.setText(_translate("MainWindow", "Augmentation !"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.preprocess_tab), _translate("MainWindow", "Préparation des données"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Paramètres"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Jeu d\'entrainement"))
        self.label_16.setText(_translate("MainWindow", "Images"))
        self.train_images_browse_button.setText(_translate("MainWindow", "..."))
        self.label_17.setText(_translate("MainWindow", "Segmentations"))
        self.train_seg_browse_button.setText(_translate("MainWindow", "..."))
        self.groupBox_14.setTitle(_translate("MainWindow", "Jeu d\'évaluation"))
        self.label_18.setText(_translate("MainWindow", "Images"))
        self.eval_images_browse_button.setText(_translate("MainWindow", "..."))
        self.label_19.setText(_translate("MainWindow", "Segmentations"))
        self.eval_seg_browse_button.setText(_translate("MainWindow", "..."))
        self.groupBox_18.setTitle(_translate("MainWindow", "Nouveau modèle"))
        self.label_33.setText(_translate("MainWindow", "Largeur des images d\'entrée"))
        self.label_34.setText(_translate("MainWindow", "Hauteur des images d\'entrée"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Modèle existant (vide pour un nouveau modèle)"))
        self.existing_model_path_browse_button.setText(_translate("MainWindow", "..."))
        self.groupBox_21.setTitle(_translate("MainWindow", "Nombre de classes"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Entrainement"))
        self.label_22.setText(_translate("MainWindow", "Taille du batch"))
        self.label_23.setText(_translate("MainWindow", "Nb d\'étapes par époque"))
        self.label_24.setText(_translate("MainWindow", "Nb d\'époques"))
        self.label_29.setText(_translate("MainWindow", "Sauvegarder dans [chemin]/[nom]"))
        self.save_model_path_browse_button.setText(_translate("MainWindow", "..."))
        self.train_button.setText(_translate("MainWindow", "Entrainement"))
        self.eval_button.setText(_translate("MainWindow", "Evaluation"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Logs"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.train_tab), _translate("MainWindow", "Entrainement"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Données"))
        self.label_25.setText(_translate("MainWindow", "Modèle"))
        self.predict_model_path_browse_button.setText(_translate("MainWindow", "..."))
        self.label_26.setText(_translate("MainWindow", "Images à prédire"))
        self.label_27.setText(_translate("MainWindow", "Enregistrer les segmentations dans"))
        self.label_28.setText(_translate("MainWindow", "Enregistrer les superpositions dans"))
        self.predict_images_browse_button.setText(_translate("MainWindow", "..."))
        self.saved_seg_browse_button.setText(_translate("MainWindow", "..."))
        self.saved_sup_browse_button.setText(_translate("MainWindow", "..."))
        self.predict_button.setText(_translate("MainWindow", "Prédire"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Logs"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab), _translate("MainWindow", "Prédiction"))
        self.action_save_conf.setText(_translate("MainWindow", "Sauvegarder cette configuration"))
        self.action_load_conf.setText(_translate("MainWindow", "Charger une configuration"))
